# Generated by Django 5.0.2 on 2024-03-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_group_product_alter_lesson_product'),
        ('student', '0002_alter_student_options_alter_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='available_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='product.group'),
        ),
    ]
