# Generated by Django 5.0.2 on 2024-03-01 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_group_product_alter_lesson_product'),
        ('student', '0004_alter_student_available_product_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='available_product',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_on_product', to='product.product'),
        ),
    ]
