# Generated by Django 5.0.2 on 2024-03-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_current_students_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='lessons',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productauthor',
            table='product_authors',
        ),
    ]
