# Generated by Django 5.0.2 on 2024-03-01 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_group_table_alter_lesson_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 10, 35, 33, 280205, tzinfo=datetime.timezone.utc)),
        ),
    ]
