# Generated by Django 5.0.2 on 2024-03-01 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
